version: '3.4'

services:
  thunderwings-api:
    image: ${DOCKER_REGISTRY-}thunderwings-api
    container_name: ThunderWings.Api
    build:
      context: .
      dockerfile: src/ThunderWings.Api/Dockerfile
    ports:
      - "5001:443"

  thunder-wings-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ThunderWings.Db
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Strong_password_123!"
